import '@/app/review/review.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-mono`}
      >
        {children}
      </body>
    </html>
  );
}
